### ISSUE TITLE
Dropping PHP support < 7.1

### ISSUE THREAD

**Issue by lex111** [linuxforphp/linuxforcomposer#1]
I think it's worth considering dropping support PHP 5.6 and 7.0 because they are no longer supported https://www.php.net/supported-versions.php

@andrewscaya what do you think?

**Comment by andrewscaya** [comment]
@lex111 Sorry for the late reply!

Even if those PHP versions are no longer supported, many PHP environments are still running under PHP 5 (many apps running Wordpress or Joomla, or simply legacy projects). Since Linux for PHP is aiming to help devs and sysadmins to migrate their legacy projects to PHP 7.1+, and that Linux for Composer is more of a utility than a production Web app, we will try to continue to cover as many PHP versions as we possibly can.

Thoughts?

**Comment by lex111** [comment]
Fair enough, I just wanted to help your project this way :)
Although I have some ideas on refactoring the code to improve the readability of code base, apart from that, I probably can't offer any other help :(

**Comment by andrewscaya** [comment]
@lex111 If you feel like doing unit tests, or proposing a new feature, please feel free to do so, ok?

**Comment by lex111** [comment]
@andrewscaya sure! I would start with an easy - a little refactoring, how do you look at it?

**Comment by andrewscaya** [comment]
@lex111 Please have a look at the new 2.0.0 release, and please refactor away! :)

**Comment by andrewscaya** [comment]
Removing 5.6, 7.0, and 7.1 from the Travis test matrix.

Done with commit a55ec21cbe07e19f7790e6fc43a3f6fb771723a5
